### Генерация случайной матрицы

Сгенерируйте матрицу, состоящую из 1000 строк и 50 столбцов, элементы которой являются случайными из нормального распределения N(1,100).

Функция для генерации чисел из нормального распределения: np.random.normal

Параметры:

loc: среднее нормального распределения (в нашем случае 1)
scale: стандартное отклонение нормального распределения (в нашем случае 10)
size: размер матрицы (в нашем случае (1000, 50))

In [1]:
import numpy as np
X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X)

[[-11.83882623  -6.31906947 -12.38535202 ...  23.31907372   0.50069995
   17.29296035]
 [ -8.41069725  -6.15231491   3.70179819 ...   6.63740525  -0.21982683
   10.80998574]
 [ -2.35939074 -11.39893468   5.83112608 ...  -5.95442007  -6.82199762
    2.47781451]
 ...
 [  5.45565585   9.41017448 -16.20972012 ... -12.05839745   2.52761191
    8.47664716]
 [  4.07438442   7.25121591   5.2577451  ...  13.77019363  27.6177812
   -9.83100153]
 [ -3.47171648 -21.43657861   2.40430546 ...  -1.45287969   2.88200798
   17.20291936]]


### Нормировка матрицы

Произведите нормировку матрицы из предыдущего задания: вычтите из каждого столбца его среднее значение, а затем поделите на его стандартное отклонение.

Функция для вычисления среднего: np.mean

Функция для вычисления стандартного отклонения: np.std

Первый параметр — матрица, для которой производятся вычисления. Также полезным будет параметр axis, который указывает, по какому измерению вычисляются среднее и стандартное отклонение (если axis=0, то по столбцам, если axis=1, то по строкам; если его не указывать, то данные величины будут вычислены по всей матрице).

In [2]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print (X_norm)

[[ 0.08274733  0.53277592  0.687812   ... -0.61657849 -1.11269921
   0.00520747]
 [ 0.65481044 -1.27160236 -0.46208358 ...  1.79373824 -1.79452769
   1.81709908]
 [-2.04683999 -1.05784424  0.11654461 ...  0.54609861 -0.66575934
  -0.76848967]
 ...
 [ 1.22420213  1.41953863 -1.38572822 ...  0.03323156 -1.41395266
   0.58350388]
 [ 1.02661719  0.10122762  1.04167153 ... -0.47950793  1.12466452
  -0.02442873]
 [-0.45055717  0.39525496 -1.39741645 ...  0.84466819 -1.12660583
   1.60977111]]


### Операции над элементами матрицы

Выведите для заданной матрицы номера строк, сумма элементов в которых превосходит 10.

Функция для подсчета суммы: np.sum

Аргументы аналогичны функциям np.mean и np.std.

К матрицам можно применять логические операции, которые будут применяться поэлементно. Соответственно, результатом такой операции будет матрица такого же размера, в ячейках которой будет записано либо True, либо False. Индексы элементов со значением True можно получить с помощью функции np.nonzero.

In [4]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
r = np.sum(Z, axis=1)
print(r)
print (np.nonzero(r > 10))

[ 9 13  7  9 27 12]
(array([1, 4, 5]),)


### Объединение матриц

Сгенерируйте две единичные матрицы (т.е. с единицами на диагонали) размера 3x3. Соедините две матрицы в одну размера 6x3.

Функция для генерации единичной матрицы: np.eye

Аргумент: число строк (или, что эквивалентно, столбцов).

Функция для вертикальной стыковки матриц: np.vstack((A, B))

In [5]:
A = np.eye(3)
B = np.eye(3)
print (A)
print (B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
AB = np.vstack((A, B))
print (AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
